// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sample.proto

/*
Package sample is a generated protocol buffer package.

It is generated from these files:
	sample.proto

It has these top-level messages:
	Empty
	GenerateResponse
*/
package sample

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GenerateResponse struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *GenerateResponse) Reset()                    { *m = GenerateResponse{} }
func (m *GenerateResponse) String() string            { return proto.CompactTextString(m) }
func (*GenerateResponse) ProtoMessage()               {}
func (*GenerateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GenerateResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*GenerateResponse)(nil), "GenerateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SampleSvc service

type SampleSvcClient interface {
	Generate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GenerateResponse, error)
}

type sampleSvcClient struct {
	cc *grpc.ClientConn
}

func NewSampleSvcClient(cc *grpc.ClientConn) SampleSvcClient {
	return &sampleSvcClient{cc}
}

func (c *sampleSvcClient) Generate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GenerateResponse, error) {
	out := new(GenerateResponse)
	err := grpc.Invoke(ctx, "/SampleSvc/Generate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SampleSvc service

type SampleSvcServer interface {
	Generate(context.Context, *Empty) (*GenerateResponse, error)
}

func RegisterSampleSvcServer(s *grpc.Server, srv SampleSvcServer) {
	s.RegisterService(&_SampleSvc_serviceDesc, srv)
}

func _SampleSvc_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleSvcServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SampleSvc/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleSvcServer).Generate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _SampleSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SampleSvc",
	HandlerType: (*SampleSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _SampleSvc_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sample.proto",
}

func init() { proto.RegisterFile("sample.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0xcc, 0x2d,
	0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x62, 0xe7, 0x62, 0x75, 0xcd, 0x2d, 0x28,
	0xa9, 0x54, 0xd2, 0xe0, 0x12, 0x70, 0x4f, 0xcd, 0x4b, 0x2d, 0x4a, 0x2c, 0x49, 0x0d, 0x4a, 0x2d,
	0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x8c, 0x4c, 0xb8, 0x38, 0x83, 0xc1, 0x46, 0x04, 0x97,
	0x25, 0x0b, 0xa9, 0x73, 0x71, 0xc0, 0xb4, 0x09, 0xb1, 0xe9, 0x81, 0x8d, 0x92, 0x12, 0xd4, 0x43,
	0x37, 0x49, 0x89, 0x21, 0x89, 0x0d, 0x6c, 0x9f, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x46, 0x0f,
	0xf5, 0xd4, 0x7f, 0x00, 0x00, 0x00,
}
